#!/bin/bash


nor=2		# number of runs


# Uncomment/modify appropriate lines in the code below as per your requirement
for (( run=1 ; run<nor+1 ; run=${run}+1 )) do
	if (($run < 31))
	then
		nohup python3 -m examples.fuzzy_pattern_tree --parameters parameters/fpt_standard_Heart.yml --run $run &
	else
		nohup python3 -m examples.pagie1 --parameters parameters/pagie1.yml --run $run --initialisation "ptc2" --min_tree_depth 2 --max_tree_depth 30 &

	fi

done
